/**
 * Tests for Zod validation schemas
 */
import { dealFormSchema, lineItemSchema, dealStatusUpdateSchema } from '@/lib/validations/deal'
import { DealStatus } from '@/lib/types/deal'

describe('Deal Validation Schemas', () => {
  describe('lineItemSchema', () => {
    it('validates a valid line item', () => {
      const validItem = {
        description: 'Steel Pipe',
        material_spec: 'API 5L X52',
        quantity: 100,
        unit: 'MT',
        required_delivery_date: '2024-03-15',
      }

      const result = lineItemSchema.safeParse(validItem)
      expect(result.success).toBe(true)
    })

    it('fails validation with missing description', () => {
      const invalidItem = {
        material_spec: 'API 5L X52',
        quantity: 100,
        unit: 'MT',
        required_delivery_date: '2024-03-15',
      }

      const result = lineItemSchema.safeParse(invalidItem)
      expect(result.success).toBe(false)
    })

    it('fails validation with negative quantity', () => {
      const invalidItem = {
        description: 'Steel Pipe',
        material_spec: 'API 5L X52',
        quantity: -100,
        unit: 'MT',
        required_delivery_date: '2024-03-15',
      }

      const result = lineItemSchema.safeParse(invalidItem)
      expect(result.success).toBe(false)
    })

    it('fails validation with zero quantity', () => {
      const invalidItem = {
        description: 'Steel Pipe',
        material_spec: 'API 5L X52',
        quantity: 0,
        unit: 'MT',
        required_delivery_date: '2024-03-15',
      }

      const result = lineItemSchema.safeParse(invalidItem)
      expect(result.success).toBe(false)
    })
  })

  describe('dealFormSchema', () => {
    const validDeal = {
      deal_number: 'DEAL-001',
      description: 'Test deal',
      currency: 'AED',
      line_items: [],
    }

    it('validates a valid deal', () => {
      const result = dealFormSchema.safeParse(validDeal)
      expect(result.success).toBe(true)
    })

    it('allows missing deal_number (auto-generated by backend)', () => {
      const invalidDeal = { ...validDeal }
      delete invalidDeal.deal_number
      const result = dealFormSchema.safeParse(invalidDeal)
      expect(result.success).toBe(true) // deal_number is optional for auto-generation
    })

    it('fails with missing description', () => {
      const invalidDeal = { ...validDeal }
      delete invalidDeal.description
      const result = dealFormSchema.safeParse(invalidDeal)
      expect(result.success).toBe(false)
    })

    it('validates with optional fields', () => {
      const dealWithOptionals = {
        deal_number: 'DEAL-001',
        description: 'Test deal',
        customer_id: '123e4567-e89b-12d3-a456-426614174000',
        customer_rfq_ref: 'RFQ-001',
        currency: 'AED',
        total_value: 100000,
        total_cost: 60000,
        estimated_margin_pct: 40,
        notes: 'Some notes',
        line_items: [],
      }

      const result = dealFormSchema.safeParse(dealWithOptionals)
      expect(result.success).toBe(true)
    })

    it('validates with line items', () => {
      const dealWithItems = {
        deal_number: 'DEAL-001',
        description: 'Test deal',
        currency: 'AED',
        line_items: [
          {
            description: 'Steel Pipe',
            material_spec: 'API 5L X52',
            quantity: 100,
            unit: 'MT',
            required_delivery_date: '2024-03-15',
          },
        ],
      }

      const result = dealFormSchema.safeParse(dealWithItems)
      expect(result.success).toBe(true)
    })

    it('fails with invalid line items', () => {
      const dealWithInvalidItems = {
        deal_number: 'DEAL-001',
        description: 'Test deal',
        currency: 'AED',
        line_items: [
          {
            description: 'Steel Pipe',
            material_spec: 'API 5L X52',
            quantity: -100, // Invalid: negative quantity
            unit: 'MT',
            required_delivery_date: '2024-03-15',
          },
        ],
      }

      const result = dealFormSchema.safeParse(dealWithInvalidItems)
      expect(result.success).toBe(false)
    })

    it('uses default currency AED', () => {
      const deal = {
        deal_number: 'DEAL-001',
        description: 'Test deal',
      }

      const result = dealFormSchema.safeParse(deal)
      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.data.currency).toBe('AED')
      }
    })
  })

  describe('dealStatusUpdateSchema', () => {
    it('validates valid statuses', () => {
      const validStatuses = Object.values(DealStatus)

      validStatuses.forEach((status) => {
        const result = dealStatusUpdateSchema.safeParse({ status })
        expect(result.success).toBe(true)
      })
    })

    it('fails with invalid status', () => {
      const result = dealStatusUpdateSchema.safeParse({ status: 'invalid_status' })
      expect(result.success).toBe(false)
    })

    it('fails with missing status', () => {
      const result = dealStatusUpdateSchema.safeParse({})
      expect(result.success).toBe(false)
    })
  })
})
